// app/layout.tsx
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

/**
 * Google Fonts（Geist Sans / Geist Mono）を設定
 * 
 * - next/font/google を使うことでフォントを最適化して読み込める
 * - variable オプションで CSS カスタムプロパティ（--font-geist-sans など）が定義される
 * - subsets は文字セット。ここでは "latin" を指定
 */
const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

/**
 * ページ共通のメタデータ
 * - ブラウザのタイトルや description に使われる
 * - app ディレクトリの仕組みにより自動的に head に適用される
 */
export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

/**
 * アプリ全体のルートレイアウト
 * 
 * - 全ページ共通で適用される <html> / <body> を定義
 * - フォント変数を body の className に付与
 * - globals.css で全体のスタイルを適用
 */
export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
                {children}
            </body>
        </html>
    );
}
